### ISSUE TITLE
Move interruptSetup() to end of setup()

### ISSUE THREAD

**Issue by MichaelAtOz** [jacoburge/TouchPad#2]
https://github.com/jacoburge/TouchPad/blob/f6df55803843bcae851e9df0eeefe3f59384a47b/Touch_Pad_V4.1/TouchPad.h#L250

Shouldn't the interrupt setup call be after the LEDs are initialised and after calibration?

**Comment by fourboards** [comment]
Yes, the LEDs should be initialised before the interrupt is setup.  I will change this now.  The capacitive touch must be calibrated after the interrupt is running since it is effected by the high frequency switching of the multiplexing used.  Thankyou for bringing this to my attention.

**Comment by MichaelAtOz** [comment]
@jacoburge are you in the midst of any other non-trivial changes ATM?
There are a few other changes I'd like to propose, via editing my fork, but if you were to dump a large change soon, I'd wait.

**Comment by fourboards** [comment]
No more changes coming for a while, feel free!
