### ISSUE TITLE
pressing Hotkeys in Programming mode (On the Go Prog)

### ISSUE THREAD

**Issue by oldviking** [jacoburge/TouchPad#5]
Hello,
I recently bought a Toucpad and when im using it with the German Keyboard Files it presses Hotkeys in the Text Editor. So the UI is messed up and you can't programm it. I tested with windows editor and other tools on Linux(Kwrite and the one in Gnome.)

Regards
Samuel

**Comment by fourboards** [comment]
Hi Samuel,

Sorry to hear you are having issues with your TouchPad.  Unfortunately, the
only way around this is to tweak the firmware slightly, the change is
documented on our support page under “Custom Firmware”, specifically
“Non-UK Keyboard Support”.  You will need to use the Arduino IDE to upload
the firmware replacing the UK keyboard files with the German ones
provided.  This should fix the issue you are seeing and while you have
Arduino setup you could try using it to program some more complex
functionality.  Hope this helps.

Thanks, Jacob

**Comment by oldviking** [comment]
This is also happening in the german keyboard files.

**Comment by fourboards** [comment]
Hi Samuel, 

Which hot keys are being pressed?

Thanks, Jacob

**Comment by oldviking** [comment]
It was a a strange usb port that din't work how it suppoed to.
